config/routes.rb
ESmart::Application.routes.draw do
  devise_for :users
=begin
  resource routes allow you to quickly declare all common routes of a particular controller.
=end

  resources :orders
  resources :line_items
  resources :carts
  resources :users
  resources :categories
  resources :products do
    resource :reviews
  end
  resources :roles
  resources :reviews
  resources :role_users
  resources :contacts,
            :controller => 'contact_us/contacts',
            :only       => [:new, :create]
  match 'contact-us' => 'contact_us/contacts#new', :as => :contact_us


  get "shipping_returns/index"
  get "payment/index"
  get "home/index"
  get "about/index"
  get "shipping_returns/index"
  get "usermanagement" => "usermanagement#index", :as => "usermanagement"
  get "dashboard" => "dashboard#index", :as => "dashboard"
  get "payment" => "payments#index", :as => "payment"

  match '/products' => 'products#index'
  match '/about' => 'about#index'
  match '/payment' => 'payments#index'
  match 'home' => 'home#index'
  match 'shipping' => 'shipping_returns#index'



  #Handling devise routes
  devise_for :users, :controllers => {:sessions => 'devise/sessions', :registrations => 'devise/registrations', :passwords => 'devise/passwords'}, :skip => [:sessions] do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    get '/register' => 'devise/registrations#new', :as => :registrations
    post '/login' => 'devise/sessions#create', :as => :user_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  ############
  #Search Bar#
  ############
  post '/search' => 'home#search', :as => 'search'

  #As mentioned in the dashboard and home controller the routes are set here to enable the search to work. Here
  #a post method is being used so that when a user searches for a product it posts the request and then fetches it by
  #returning the @result which is found in either controllers

   root :to => 'home#index' #Root of the application
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  load_and_authorize_resource :class => DashboardController
 #skip_before_filter :authenticate_user!, :only => :index
  #before_filter :authenticate_user!
  # load_and_authorize_resource :user, :parent => false
#  before_filter :admin_user, :only => [:create, :new, :index, :update]


  def search
    @result = nil

    respond_to do |format|
      format.html do
        if @result.nil?
          redirect_to(:root, :error => 'No records found')
        else
          redirect_to(@result)
        end
      end
      format.js
    end
  end
end

=begin
The above search method sets a results variable sets it to nil,
the respond_to block is get to format teh results in html.
If @results is zero redirect user back to the root path and display
error message 'No records found' else redirect to @result which will be
the product
=end

app/views/dashboard/index.html.erb
<%= start_icon_menu %>
<%= icon_menu_item "Products", "admin.png", products_path %>
<%= icon_menu_item "Orders", "admin.png", orders_path %>
<%= icon_menu_item "Users", "admin.png", usermanagement_path %>
<%= icon_menu_item "Categories", "admin.png", categories_path %>
<%= icon_menu_item "My Account", "admin.png", user_path(current_user)%>
<%= end_icon_menu   %>


<!--Dashboard <-<%#= start_icon_menu %> is based on the method based in "helper/application_helper.rb" This displays
layout for Administrator to have access to different sections.
->

app/views/dashboard/search.js.erb
<% if @result.nil? %>
alert( "No records found" );
<% else %>
location.href='<%= url_for(@result) %>';
<% end %>

/*If the result is nil then display the alert "No Records found" if the results are found then redirect to the results.*/