config/routes.rb
ESmart::Application.routes.draw do
  devise_for :users
=begin
  resource routes allow you to quickly declare all common routes of a particular controller.
=end

  resources :orders
  resources :line_items
  resources :carts
  resources :users
  resources :categories
  resources :products do
    resource :reviews
  end
  resources :roles
  resources :reviews
  resources :role_users
  resources :contacts,
            :controller => 'contact_us/contacts',
            :only       => [:new, :create]
  match 'contact-us' => 'contact_us/contacts#new', :as => :contact_us


  get "shipping_returns/index"
  get "payment/index"
  get "home/index"
  get "about/index"
  get "shipping_returns/index"
  get "usermanagement" => "usermanagement#index", :as => "usermanagement"
  get "dashboard" => "dashboard#index", :as => "dashboard"
  get "payment" => "payments#index", :as => "payment"

  match '/products' => 'products#index'
  match '/about' => 'about#index'
  match '/payment' => 'payments#index'
  match 'home' => 'home#index'
  match 'shipping' => 'shipping_returns#index'



  #Handling devise routes
  devise_for :users, :controllers => {:sessions => 'devise/sessions', :registrations => 'devise/registrations', :passwords => 'devise/passwords'}, :skip => [:sessions] do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    get '/register' => 'devise/registrations#new', :as => :registrations
    post '/login' => 'devise/sessions#create', :as => :user_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  ############
  #Search Bar#
  ############
  post '/search' => 'home#search', :as => 'search'

  #As mentioned in the dashboard and home controller the routes are set here to enable the search to work. Here
  #a post method is being used so that when a user searches for a product it posts the request and then fetches it by
  #returning the @result which is found in either controllers

   root :to => 'home#index' #Root of the application
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #load_and_authorize_resource
  def index

    @counter = session[:counter]                           #Create a new method counter take passes in the counter object
    @counter.nil? ? @counter = 1 : @counter+=1             #check if the counter is nil and then increments it to the counter and passes
    session[:counter] = @counter                           # it back through.

    @cart = current_cart                                   #Get current cart
  end

  def search
    @result = nil

    respond_to do |format|
      format.html do
        if @result.nil?
          redirect_to(:root, :error => 'No records found')
        else
          redirect_to(@result)
        end
      end
      format.js
    end
  end
end

=begin
The above search method sets a results variable sets it to nil,
the respond_to block is get to format teh results in html.
If @results is zero redirect user back to the root path and display
error message 'No records found' else redirect to @result which will be
the product
=end

app/views/home/index.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')</script>


<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide carousel-fade">
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("ocz-promo.jpg") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>About</h1>
          <p class="lead">At E-Smart we are offering you a great range of products at an affordable price, whilst offering you the best
            online shopping experience. Offering a wide range computer peripherals and components at valuable prices.
          </p><br /><br /><br /><br /><br /><br /><br />
          <a class="btn btn-large btn-primary" href="<%= about_path %>">About</a>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag("nvidia_promo.jpg")%>
      <div class="container">
        <div class="carousel-caption">
          <h1>Sign Up!</h1>
          <p class="lead">Sign up today and recieve benefical promotional offers</p>
          <a class="btn btn-large btn-primary" href="<%= registrations_path %>">Sign up today</a>

        </div>
      </div>
    </div>
    <div class="item">
     <%=  image_tag("intel_promo.jpg") %>

    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <!--html5 data attribute passes previous and next to the id "myCarousel" -->
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->
<center>
  <footer>
    <%= image_tag("Reassurance.gif") %>
  </footer>
  <footer>
    <p>&copy; Copyright E-Smart 2013 </p>
    <b><h3><span class="label label-important">NOT A REAL SHOP!</span></h3></b>
  </footer>
</center>

app/views/home/search.js.erb
<% if @result.nil? %>
alert( "No records found" );
<% else %>
location.href='<%= url_for(@result) %>';
<% end %> 