config/routes.rb
ESmart::Application.routes.draw do
  devise_for :users
=begin
  resource routes allow you to quickly declare all common routes of a particular controller.
=end

  resources :orders
  resources :line_items
  resources :carts
  resources :users
  resources :categories
  resources :products do
    resource :reviews
  end
  resources :roles
  resources :reviews
  resources :role_users
  resources :contacts,
            :controller => 'contact_us/contacts',
            :only       => [:new, :create]
  match 'contact-us' => 'contact_us/contacts#new', :as => :contact_us


  get "shipping_returns/index"
  get "payment/index"
  get "home/index"
  get "about/index"
  get "shipping_returns/index"
  get "usermanagement" => "usermanagement#index", :as => "usermanagement"
  get "dashboard" => "dashboard#index", :as => "dashboard"
  get "payment" => "payments#index", :as => "payment"

  match '/products' => 'products#index'
  match '/about' => 'about#index'
  match '/payment' => 'payments#index'
  match 'home' => 'home#index'
  match 'shipping' => 'shipping_returns#index'



  #Handling devise routes
  devise_for :users, :controllers => {:sessions => 'devise/sessions', :registrations => 'devise/registrations', :passwords => 'devise/passwords'}, :skip => [:sessions] do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    get '/register' => 'devise/registrations#new', :as => :registrations
    post '/login' => 'devise/sessions#create', :as => :user_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  ############
  #Search Bar#
  ############
  post '/search' => 'home#search', :as => 'search'

  #As mentioned in the dashboard and home controller the routes are set here to enable the search to work. Here
  #a post method is being used so that when a user searches for a product it posts the request and then fetches it by
  #returning the @result which is found in either controllers

   root :to => 'home#index' #Root of the application
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name #Accessible attribute "name"

  #Association
  has_many :products #Categories have many products

  CATEGORIES = [ "Processor", "Graphics", "Networking", "Storage" ] #Pre-defined Categories.
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

=begin
The first before_filter :admin only allows admin users to do the following actions. This is set in the application
controller.

Second before_filter authenticates normal users giving them access to only view the show action. This will mean that
normal users or non-logged in users CANNOT CRUD categories. If they attempt this they will be redirected to the root
path
=end

  before_filter :admin, :only => [:new, :edit, :create, :destroy, :update]
  before_filter :authenticate, :except => [:show]


  def index
    @categories = Category.all # Find all categories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id]) #Find and display all categories and products related to particular category
    @products = @category.products #Cat the products to the categories.
    @cart = current_cart                                   #Get current cart

  end

  def new
    @category = Category.new #Create a new category and set it to be empty. When the _form.html.erb is being used it will

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end

    def edit
      @category = Category.find(params[:id]) #This finds the category using the .find() and pass the category :id into the
                                             #params allowing us to edit the cateory.
    end

    def create
      @category = Category.new(params[:category]) #Create new category based on parameter passed in `:category'`

      respond_to do |format|
        if @category.save
          #If category infomration is successful then diaplay and output below html notice and redirect back to the category path
          format.html { redirect_to :back, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created, location: @category }
        else
          #Else if the category is not save the render 'new' action.
          format.html { render action: "new" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @category = Category.find(params[:id]) #Find the edited category and pass in Category id.

      respond_to do |format|
        if @category.update_attributes(params[:category])
          #If the updated attributes are successful then output successul notice and render @category path
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          #Else continue to call the 'edit' action.
          format.html { render action: "edit" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy

    @category = Category.find(params[:id]) #Find cateogy id that will be deleted.
    if @category.products.count == 0 #Check using .count() to determine if category has products == 0
      @category.destroy #If no products then delete category
      flash[:success] = 'Category has been deleted.' #Once deleted display flash success message
      redirect_to categories_path
    else #Else there are products related to category then category will not be deleted and then redirected back to
         #category index path
      flash[:error] = "Category can't be deleted, there are products related to this category"
      redirect_to categories_path
    end
  end
end

app/views/categories/_form.html.erb
<!--The form is automatically generated when the 'rails scaffold' command is executed. -->

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>   <!--Renders the partial _form.html.erb-->

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!--Basic standard generated view when 'rails generate scaffold command is ran-->

<h1>Listing categories</h1>

<table class="table table-striped table-bordered">
 <thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_category_path(category), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class =>  'btn btn-mini btn-danger' %></td>
  </tr>
     <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path, :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %> <!--Render partial _form.html.erb, however controller action renders new action-->

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>   <!--Get category name-->
<table class="row-fluid">
  <!--Loop the products -->
  <% @products.each do |product| %>
      <td rowspan="3"> <%= image_tag(product.image, :size => "250x250") %></td>
      <!--Get product image and set size to 250 x 250-->
      <td colspan="2"> <h3><%= product.title %></h3>  </td>
      <!--Get produt title-->
      </tr>
      <tr>
        <td colspan="2"><%= product.description %> <br />    <!--Get product description-->
          <% if stock_left(product) == 0 %>
              <!--The above "if" stock_left passes in the product which has been defined in the
     "helper/product_helper.rb This calculates how much stock is left  -->
              <span class="label label-important ">SOLD OUT</span> <!--Display "SOLD OUT if stock is 0-->
          <% elsif stock_left(product) < 5 %>
              <span class="label label-warning "> ONLY <%= product.stock %> Left </span><!--Display how much stock left-->

          <% else stock_left(product) > 5 %> <!--If stock is greater than 5 then display "IN STOCK"-->
              <span class="label label-success "> IN STOCK </span>
          <% end %>
          <% if product.price < 90 %>   <!--If product price is less than 90 display the following-->
              <span class="label label-important">Special offer <%= number_to_currency(product.price, :unit => "&pound;") %></span>
          <% else %>
              <span class="label "><%= number_to_currency(product.price, :unit => "&pound;") %></span>
          <% end %>
          <%= link_to 'Show', product, :class => 'btn btn-primary btn-mini '%>

          <% if stock_left(product) == 0 %>
              <%= button_to 'Add to Cart', line_items_path(:product_id => product), :class => 'btn btn-primary btn-mini ',  :disabled => true%> <!--disable button if no stock-->
          <% else %>
              <%= button_to 'Add to Cart', line_items_path(:product_id => product), :class => 'btn btn-primary btn-mini '%>
          <% end  %>
        </td>
      </tr>
      <tr>
        <td>
        </td>
      </tr>
      <tr>
        <td colspan="3"> <!--Set column span to 3 -->
          <hr /> <!--Defines a thematic break  -->
        </td>
      </tr>
  <% end %>  <!--End loop -->
</table>
<center>
  <footer>
    <%= image_tag("Reassurance.gif") %>
  </footer>
  <footer>
    <p>&copy; Copyright E-Smart 2013 </p>
    <b><h3><span class="label label-important">NOT A REAL SHOP!</span></h3></b>
  </footer>
</center>